import { statusToString } from '../statusToString'

test('statusToString', () => {
  expect(statusToString(114)).toBe('Validation Delayed')
  expect(statusToString(118)).toBe('Rate Limit Exceeded')
  expect(statusToString(119)).toBe('API Key Invalid or Depleted')
  expect(statusToString(121)).toBe('Task Accepted')
  expect(statusToString(200)).toBe('OK - Valid Address')
  expect(statusToString(207)).toBe('OK - Catch-All Active')
  expect(statusToString(215)).toBe('OK - Catch-All Test Delayed')
  expect(statusToString(302)).toBe('Local Address')
  expect(statusToString(303)).toBe('IP Address Literal')
  expect(statusToString(305)).toBe('Disposable Address')
  expect(statusToString(308)).toBe('Role Address')
  expect(statusToString(313)).toBe('Server Unavailable')
  expect(statusToString(314)).toBe('Address Unavailable')
  expect(statusToString(316)).toBe('Duplicate Address')
  expect(statusToString(317)).toBe('Server Reject')
  expect(statusToString(401)).toBe('Bad Address')
  expect(statusToString(404)).toBe('Domain Not Fully Qualified')
  expect(statusToString(406)).toBe('MX Lookup Error')
  expect(statusToString(409)).toBe('No-Reply Address')
  expect(statusToString(410)).toBe('Address Rejected')
  expect(statusToString(413)).toBe('Server Unavailable')
  expect(statusToString(414)).toBe('Address Unavailable')
  expect(statusToString(420)).toBe('Domain Name Misspelled')
  expect(statusToString(0)).toBe('Unknown Status Code')
})
